### ISSUE TITLE
Replacing fights that have a / in their title does not work

### ISSUE THREAD

**Issue by KingWowowood** [snelson3/kh2fm-spawn-replacer#2]
While trying to edit the fight for "I/O Tower Heartless Fight" and "Pain/Panic Round 10" command prompt comes up with the error "FileNotFoundError: [Errno 2] No such file or directory: 'i/o_tower_heartless_fight.yaml'" (same thing for the Pain/Panic Round 10, just with its title instead of the i/o one of course). I can't tell whether I am supposed to type it in a different way for titles with a / in them or if these are just broken in some way currently.
(here's an example of it not working with Pain/Panic, and showing that it's spelled the same way as in the readme and locations.json)
![Screenshot (166)](https://user-images.githubusercontent.com/53595449/98432581-753a9200-2074-11eb-9c3f-8c617f7243ca.png)
Update: I got it to work by going into the locations.json file and renaming the fights themselves, I think that this should be done by default if it is possible for this quick fix to be made

**Comment by snelson3** [comment]
Pushed fix, now the script will change "/" to "_" when creating the filename
